# Generated by Django 5.2.12 on 2026-04-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_id_alter_generation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
